# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 496962c52bd78e884284346d8a5e8ee19813fe1133b34d200c1691fed2defe72d3dbb479d94427c4bab2d382ec176e766c4e76563e4d0fa2a1ff19c68d0b34b3

test:
  secret_key_base: 5e48270ef984806afcb6007fd4bb496b930b2b48e94910129458f4ab63629da091256d21420cf4b0e0a2bd95cacf127f23cdcc69921c3180618e35db5b1c8616

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
